//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.ComponentModel;
using System.Data.EntityClient;
using System.Data.Objects;
using System.Data.Objects.DataClasses;
using System.Linq;
using System.Runtime.Serialization;
using System.Xml.Serialization;

[assembly: EdmSchemaAttribute()]
namespace Dairy_ERPModel
{
    #region Contexts
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    public partial class Dairy_ERPEntities : ObjectContext
    {
        #region Constructors
    
        /// <summary>
        /// Initializes a new Dairy_ERPEntities object using the connection string found in the 'Dairy_ERPEntities' section of the application configuration file.
        /// </summary>
        public Dairy_ERPEntities() : base("name=Dairy_ERPEntities", "Dairy_ERPEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new Dairy_ERPEntities object.
        /// </summary>
        public Dairy_ERPEntities(string connectionString) : base(connectionString, "Dairy_ERPEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new Dairy_ERPEntities object.
        /// </summary>
        public Dairy_ERPEntities(EntityConnection connection) : base(connection, "Dairy_ERPEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        #endregion
    
        #region Partial Methods
    
        partial void OnContextCreated();
    
        #endregion
    
        #region ObjectSet Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<personalinfo> personalinfoes
        {
            get
            {
                if ((_personalinfoes == null))
                {
                    _personalinfoes = base.CreateObjectSet<personalinfo>("personalinfoes");
                }
                return _personalinfoes;
            }
        }
        private ObjectSet<personalinfo> _personalinfoes;

        #endregion

        #region AddTo Methods
    
        /// <summary>
        /// Deprecated Method for adding a new object to the personalinfoes EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddTopersonalinfoes(personalinfo personalinfo)
        {
            base.AddObject("personalinfoes", personalinfo);
        }

        #endregion

    }

    #endregion

    #region Entities
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="Dairy_ERPModel", Name="personalinfo")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class personalinfo : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new personalinfo object.
        /// </summary>
        /// <param name="sno">Initial value of the sno property.</param>
        public static personalinfo Createpersonalinfo(global::System.Int32 sno)
        {
            personalinfo personalinfo = new personalinfo();
            personalinfo.sno = sno;
            return personalinfo;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 sno
        {
            get
            {
                return _sno;
            }
            set
            {
                if (_sno != value)
                {
                    OnsnoChanging(value);
                    ReportPropertyChanging("sno");
                    _sno = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("sno");
                    OnsnoChanged();
                }
            }
        }
        private global::System.Int32 _sno;
        partial void OnsnoChanging(global::System.Int32 value);
        partial void OnsnoChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String name
        {
            get
            {
                return _name;
            }
            set
            {
                OnnameChanging(value);
                ReportPropertyChanging("name");
                _name = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("name");
                OnnameChanged();
            }
        }
        private global::System.String _name;
        partial void OnnameChanging(global::System.String value);
        partial void OnnameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String mobno
        {
            get
            {
                return _mobno;
            }
            set
            {
                OnmobnoChanging(value);
                ReportPropertyChanging("mobno");
                _mobno = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("mobno");
                OnmobnoChanged();
            }
        }
        private global::System.String _mobno;
        partial void OnmobnoChanging(global::System.String value);
        partial void OnmobnoChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String email
        {
            get
            {
                return _email;
            }
            set
            {
                OnemailChanging(value);
                ReportPropertyChanging("email");
                _email = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("email");
                OnemailChanged();
            }
        }
        private global::System.String _email;
        partial void OnemailChanging(global::System.String value);
        partial void OnemailChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String msgtype
        {
            get
            {
                return _msgtype;
            }
            set
            {
                OnmsgtypeChanging(value);
                ReportPropertyChanging("msgtype");
                _msgtype = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("msgtype");
                OnmsgtypeChanged();
            }
        }
        private global::System.String _msgtype;
        partial void OnmsgtypeChanging(global::System.String value);
        partial void OnmsgtypeChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> branchid
        {
            get
            {
                return _branchid;
            }
            set
            {
                OnbranchidChanging(value);
                ReportPropertyChanging("branchid");
                _branchid = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("branchid");
                OnbranchidChanged();
            }
        }
        private Nullable<global::System.Int32> _branchid;
        partial void OnbranchidChanging(Nullable<global::System.Int32> value);
        partial void OnbranchidChanged();

        #endregion

    
    }

    #endregion

    
}
